import { z } from "zod";

const configSchema = z.object({
  rangeYears: z.string(),
  rsiPeriod: z.number().int().positive(),
  rsiOversold: z.number().positive(),
  nearSupportPct: z.number().positive(),
  stopBufferPct: z.number().positive(),
  maxTpPct: z.number().positive(),
  minRR: z.number().positive(),
  minAdvIdr: z.number().positive(),
  capital: z.number().positive(),
  riskPerTradePct: z.number().positive(),
  topN: z.number().int().positive(),
  generatedWatchlistPath: z.string().min(1),
  swingK: z.number().int().positive(),
  swingTolPct: z.number().positive(),
  divWindow: z.number().int().positive(),
  weekly: z.object({
    topN: z.number().int().positive(),
    minHistoryDays: z.number().int().positive(),
    minAdvIdr: z.number().positive(),
    nearSupportPct: z.number().positive(),
    maxAtrPct: z.number().positive(),
    maxBelowSma50Pct: z.number().nonnegative(),
  }),
  daily: z.object({
    requireReversalConfirm: z.boolean(),
    maxBelowSma50Pct: z.number().positive(),
    cooldownDays: z.number().int().nonnegative(),
  }),
  strategy: z.object({
    mode: z.enum(["pullback", "reversal"]),
    requireAboveSma50: z.boolean(),
    rsiPullbackMax: z.number().positive(),
    pullbackLookback: z.number().int().positive(),
    pullbackMinPct: z.number().nonnegative(),
    pullbackMaxPct: z.number().positive(),
    sma20BandPct: z.number().positive(),
    sma20RequireRising: z.boolean(),
    triggers: z.object({
      rsi: z.boolean(),
      pullbackPct: z.boolean(),
      sma20Tag: z.boolean(),
    }),
    reversalRequireDivergence: z.boolean(),
  }),
  signalStatePath: z.string().min(1),
  flow: z.object({
    enabled: z.boolean(),
    cmfPeriod: z.number().int().positive(),
    minCmf: z.number(),
    volLookback: z.number().int().positive(),
  }),
  weights: z.object({
    rr: z.number(),
    divergence: z.number(),
    confluence: z.number(),
    oversold: z.number(),
    liquidity: z.number(),
    flow: z.number(),
  }),
  backtest: z.object({
    years: z.string(),
    warmupDays: z.number().int().positive(),
    maxHoldDays: z.number().int().positive(),
    costPct: z.number().nonnegative(),
    snapshotPath: z.string().min(1),
    oosSplitFraction: z.number().gt(0).lt(1),
  }),
  provider: z.object({
    maxRetries: z.number().int().nonnegative(),
    retryBaseMs: z.number().int().positive(),
    maxStaleDays: z.number().int().positive(),
  }),
  runLogPath: z.string().min(1),
  paperTradesPath: z.string().min(1),
  requestDelayMs: z.number().int().nonnegative(),
});

export const CONFIG = configSchema.parse({
  rangeYears: "2y",
  rsiPeriod: 14,
  rsiOversold: 35,
  nearSupportPct: 3,
  stopBufferPct: 1.5,
  maxTpPct: 5,
  minRR: 1.5,
  minAdvIdr: 5_000_000_000,
  capital: 100_000_000,
  riskPerTradePct: 1,
  topN: 5,
  generatedWatchlistPath: "data/watchlist.generated.json",
  swingK: 3,
  swingTolPct: 0.7,
  divWindow: 40,
  weekly: {
    topN: 40,
    minHistoryDays: 120,
    minAdvIdr: 5_000_000_000,
    nearSupportPct: 8,
    maxAtrPct: 8,
    maxBelowSma50Pct: 8,
  },
  daily: {
    requireReversalConfirm: true,
    maxBelowSma50Pct: 12,
    cooldownDays: 5,
  },
  strategy: {
    mode: "pullback",
    requireAboveSma50: true,
    rsiPullbackMax: 50,
    pullbackLookback: 20,
    pullbackMinPct: 3,
    pullbackMaxPct: 12,
    sma20BandPct: 2,
    sma20RequireRising: true,
    triggers: {
      rsi: true,
      pullbackPct: true,
      sma20Tag: false,
    },
    reversalRequireDivergence: false,
  },
  signalStatePath: "data/signal-state.json",
  flow: {
    enabled: false,
    cmfPeriod: 20,
    minCmf: -0.1,
    volLookback: 20,
  },
  weights: {
    rr: 2,
    divergence: 1.5,
    confluence: 1,
    oversold: 0.05,
    liquidity: 0.0000000005,
    flow: 0,
  },
  backtest: {
    years: "5y",
    warmupDays: 150,
    maxHoldDays: 30,
    costPct: 0.3,
    snapshotPath: "data/backtest-snapshot.json",
    oosSplitFraction: 0.6,
  },
  provider: {
    maxRetries: 3,
    retryBaseMs: 800,
    maxStaleDays: 5,
  },
  runLogPath: "data/run-log.jsonl",
  paperTradesPath: "data/paper-trades.jsonl",
  requestDelayMs: 400,
});
