import { z } from "zod";

const configSchema = z.object({
  rangeYears: z.string(),
  rsiPeriod: z.number().int().positive(),
  rsiOversold: z.number().positive(),
  nearSupportPct: z.number().positive(),
  stopBufferPct: z.number().positive(),
  maxTpPct: z.number().positive(),
  minRR: z.number().positive(),
  minAdvIdr: z.number().positive(),
  capital: z.number().positive(),
  riskPerTradePct: z.number().positive(),
  topN: z.number().int().positive(),
  generatedWatchlistPath: z.string().min(1),
  swingK: z.number().int().positive(),
  swingTolPct: z.number().positive(),
  divWindow: z.number().int().positive(),
  weekly: z.object({
    topN: z.number().int().positive(),
    minHistoryDays: z.number().int().positive(),
    minAdvIdr: z.number().positive(),
    nearSupportPct: z.number().positive(),
    maxAtrPct: z.number().positive(),
    maxBelowSma50Pct: z.number().nonnegative(),
  }),
  daily: z.object({
    requireReversalConfirm: z.boolean(),
    maxBelowSma50Pct: z.number().positive(),
    cooldownDays: z.number().int().nonnegative(),
  }),
  signalStatePath: z.string().min(1),
  weights: z.object({
    rr: z.number(),
    divergence: z.number(),
    confluence: z.number(),
    oversold: z.number(),
    liquidity: z.number(),
  }),
  backtest: z.object({
    years: z.string(),
    warmupDays: z.number().int().positive(),
    maxHoldDays: z.number().int().positive(),
    costPct: z.number().nonnegative(),
  }),
  provider: z.object({
    maxRetries: z.number().int().nonnegative(),
    retryBaseMs: z.number().int().positive(),
    maxStaleDays: z.number().int().positive(),
  }),
  runLogPath: z.string().min(1),
  requestDelayMs: z.number().int().nonnegative(),
});

export const CONFIG = configSchema.parse({
  rangeYears: "2y",
  rsiPeriod: 14,
  rsiOversold: 35,
  nearSupportPct: 3,
  stopBufferPct: 1.5,
  maxTpPct: 5,
  minRR: 1.5,
  minAdvIdr: 5_000_000_000,
  capital: 100_000_000,
  riskPerTradePct: 1,
  topN: 5,
  generatedWatchlistPath: "data/watchlist.generated.json",
  swingK: 3,
  swingTolPct: 0.7,
  divWindow: 40,
  weekly: {
    topN: 40,
    minHistoryDays: 120,
    minAdvIdr: 5_000_000_000,
    nearSupportPct: 8,
    maxAtrPct: 8,
    maxBelowSma50Pct: 8,
  },
  daily: {
    requireReversalConfirm: true,
    maxBelowSma50Pct: 12,
    cooldownDays: 5,
  },
  signalStatePath: "data/signal-state.json",
  weights: {
    rr: 2,
    divergence: 1.5,
    confluence: 1,
    oversold: 0.05,
    liquidity: 0.0000000005,
  },
  backtest: {
    years: "5y",
    warmupDays: 150,
    maxHoldDays: 30,
    costPct: 0.3,
  },
  provider: {
    maxRetries: 3,
    retryBaseMs: 800,
    maxStaleDays: 5,
  },
  runLogPath: "data/run-log.jsonl",
  requestDelayMs: 400,
});
